name: Deploy to Github Pages
on:
  push:
    branches:
      - web
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          # type configurations: your user.email and user.name followed lines 
          git config --global user.email yusef.ouda@outlook.com
          git config --global user.name yusefouda
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/yusefouda/lurkers-for-reddit.git
          git checkout -b gh-pages
          echo "lurkers.yusefouda.com" >> CNAME
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
